# Generated by Django 4.2.6 on 2023-10-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightreservation',
            old_name='departure_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='flightreservation',
            name='departure_city',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flightreservation',
            name='destination_city',
            field=models.CharField(max_length=10),
        ),
    ]
